name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.ASSISTANT_SERVER}}
          key: ${{secrets.ASSISTANT_SERVER_TOKEN}}
          port: ${{secrets.ASSISTANT_SERVER_PORT}}
          username: ${{secrets.ASSISTANT_SERVER_USER}}
          debug: true
          script: |
            cd project/The-ASSistant
            git restore .
            git pull --ff-only
            composer install
            echo If migrations were changed, remember to run php artisan migrate.
