name: Laravel

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_assistant_rsa
          sudo chmod 600 ~/.ssh/id_assistant_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_assistant_rsa
          ssh -vvv -tt -i ~/.ssh/id_assistant_rsa -p ${{secrets.ASSISTANT_SERVER_PORT}} ${{secrets.ASSISTANT_SERVER_USER}}@${{secrets.ASSISTANT_SERVER}}
          sudo git pull
          exit
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.ASSISTANT_SERVER_TOKEN}}
          SSH_KNOWN_HOSTS: ${{secrets.ASSISTANT_KNOWN_HOSTS}}
